version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uspos
    ports:
      - "5432:5432"

  api:
    build: .
    command: [ "make", "start-api" ]
    # volumes:
    #   - .:/app

    ports:
      - "8000:8000"

    depends_on:
      - db

    # env_file:
    #   - ./.env

    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: uspos
      DB_HOST: db
      DB_PORT: 5432

# volumes:
#   db:
#     driver: local
