version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uspos
    ports:
      - "5433:5432"

  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0

    volumes:
      - .:/app

    ports:
      - "8001:8000"

    depends_on:
      - db

    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB: uspos

volumes:
  db:
    driver: local
