# Generated by Django 4.2.6 on 2023-10-27 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu_merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='menu_merchant.merchant'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='menu_merchant.product'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='menu_merchant.service'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu_merchant.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='products', to='menu_merchant.hashtag'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='products', to='menu_merchant.keyword'),
        ),
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu_merchant.merchant'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchant',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='merchants', to='menu_merchant.category'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='merchants', to='menu_merchant.hashtag'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='merchants', to='menu_merchant.keyword'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='menu_merchant.merchant'),
        ),
        migrations.AddField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='hashtag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='menu_merchant.hashtag'),
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='menu_merchant.category'),
        ),
    ]
